# Generated by Django 5.2.8 on 2025-12-14 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('فوق لیسانس', 'فوق لیسانس'), ('دکتری', 'دکتری'), ('سایر', 'سایر')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='user_app/images/default.jpg', null=True, upload_to='user_app/images/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
