# Generated by Django 5.2.5 on 2025-10-14 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='profile',
        ),
    ]
