# Generated by Django 5.2.5 on 2025-10-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_remove_task_profile'),
        ('user_app', '0003_remove_userprofile_bio_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.userprofile'),
        ),
    ]
