# Generated by Django 5.2.5 on 2025-10-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_remove_task_user_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=10),
        ),
    ]
